on:
  workflow_call:
    inputs:
      comparison:
        type: string
        description: 'The comparison to use for the mutation testing'
        required: true
env:
  MAJOR_DOTNET_VERSION: 8
  TestPath: /home/runner/work/Html2Markdown/Html2Markdown/test/Html2Markdown.Test/Files/
  STRYKER_VERSION: 4.8.1
        
jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: ${{ env.MAJOR_DOTNET_VERSION }}.0.x
      - name: Install Stryker
        run: |
          dotnet tool install -g dotnet-stryker --version $STRYKER_VERSION
      - name: Run Stryker
        env:
          COMPARISON: ${{ inputs.comparison }}
        run: |
          dotnet stryker --since:$COMPARISON
      - name: Upload Report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v5
        with:
          name: Mutation-Report
          path: ./StrykerOutput/*/reports/mutation-report.html